server:
  port: 8121

spring:
  profiles:
    active: dev
  application:
    name: service-oss
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

aliyun:
  oss:
    endpoint: 你的endponit
    keyid: 你的阿里云keyid
    keysecret: 你的阿里云keysecret
    #bucket可以在控制台创建，也可以使用java代码创建，注意先测试bucket是否已被占用
    bucketname: guli-file