server:
  port: 8110 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-edu # 服务名
  datasource: # mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.10.111.13:3306/dispatcher?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: dispatcher_rw
    password: haoshikisses
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#    sentinel: #需要单独启动一个sentinel
#      transport:
#        port: 8081 #跟控制台交流的端口，随意指定一个未使用的端口即可
#        dashboard: localhost:8080 # 指定控制台服务的地址

  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

ribbon:
  MaxAutoRetries: 0 # 同一实例最大重试次数，不包括首次调用，默认0
  MaxAutoRetriesNextServer: 1 # 重试其他实例的最大重试次数，不包括首次所选的server，默认1
  ConnectionTimeout: 5000 #连接建立的超时时长，默认1秒
  ReadTimeout: 5000 #处理请求的超时时间，默认为1秒

feign:
  sentinel:
    enabled: true

logging:
  level:
    com.study.edu.feign.OssFileService: debug #以什么级别监控哪个接口
